# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[build-system]
requires = ["setuptools>=61", "wheel", "cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["pyiceberg*", "vendor/fb303*", "vendor/hive_metastore*"]

[tool.setuptools.package-data]
"*" = ["*.so", "*.pyd", "*.pyx"]

[tool.setuptools.exclude-package-data]
pyiceberg = ["*.pyc",'*.py']

[tool.cibuildwheel]
environment = {CIBW_BUILD_FRONTEND="build[uv]"}

[[tool.cibuildwheel.overrides]]
select = "cp3{9,10,11,12}-*"

[tool.uv]
no-build-isolation-package = ["cython"]

[project]
name = "pyiceberg"
version = "0.10.0"
description = "Apache Iceberg is an open table format for huge analytic datasets"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Apache Software Foundation", email = "dev@iceberg.apache.org" }
]
requires-python = ">=3.9.2,!=3.9.7"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "mmh3>=4.0.0,<6.0.0",
    "requests>=2.20.0,<3.0.0",
    "click>=7.1.1,<9.0.0",
    "rich>=10.11.0,<15.0.0",
    "strictyaml>=1.7.0,<2.0.0",
    "pydantic>=2.0,<3.0,!=2.4.0,!=2.4.1",
    "sortedcontainers==2.4.0",
    "fsspec>=2023.1.0",
    "pyparsing>=3.1.0,<4.0.0",
    "zstandard>=0.13.0,<1.0.0",
    "tenacity>=8.2.3,<10.0.0",
    "pyroaring>=1.0.0,<2.0.0",
    "cachetools>=5.5,<7.0",
]

[project.optional-dependencies]
pyarrow = ["pyarrow>=17.0.0,<21.0.0"]
pandas = ["pandas>=1.0.0,<3.0.0", "pyarrow>=17.0.0,<21.0.0"]
duckdb = ["duckdb>=0.5.0,<2.0.0", "pyarrow>=17.0.0,<21.0.0"]
ray = [
    "ray==2.10.0; python_version<'3.9'",
    "ray>=2.10.0,<3.0.0; python_version>='3.9'",
    "pyarrow>=17.0.0,<21.0.0",
    "pandas>=1.0.0,<3.0.0",
]
daft = ["getdaft>=0.2.12"]
polars = ["polars>=1.21.0"]
snappy = ["python-snappy>=0.6.0,<1.0.0"]
hive = ["thrift>=0.13.0,<1.0.0"]
hive-kerberos = [
    "thrift>=0.13.0,<1.0.0",
    "thrift-sasl>=0.4.3",
    "kerberos>=1.3.1",
]
s3fs = ["s3fs>=2023.1.0"]
glue = ["boto3>=1.24.59", "mypy-boto3-glue>=1.28.18"]
adlfs = ["adlfs>=2023.1.0"]
dynamodb = ["boto3>=1.24.59"]
zstandard = ["zstandard>=0.13.0,<1.0.0"]
sql-postgres = ["sqlalchemy>=2.0.18", "psycopg2-binary>=2.9.6"]
sql-sqlite = ["sqlalchemy>=2.0.18"]
gcsfs = ["gcsfs>=2023.1.0"]
rest-sigv4 = ["boto3>=1.24.59"]
hf = ["huggingface-hub>=0.24.0"]
pyiceberg-core = ["pyiceberg-core>=0.4.0"]

[project.scripts]
pyiceberg = "pyiceberg.cli.console:run"

[project.urls]
Homepage = "https://py.iceberg.apache.org/"
Repository = "https://github.com/apache/iceberg-python"

[dependency-groups]
dev = [
    "pytest==7.4.4",
    "pytest-checkdocs==2.13.0",
    "pytest-lazy-fixture==0.6.3",
    "pre-commit==4.2.0",
    "fastavro==1.11.1",
    "coverage[toml]>=7.4.2",
    "requests-mock==1.12.1",
    "moto[server]>=5.0.2",
    "typing-extensions==4.13.2",
    "pytest-mock==3.14.1",
    "pyspark==3.5.6",
    "cython==3.1.1",
    "deptry>=0.14,<0.24",
    "datafusion>=44,<48",
    "docutils!=0.21.post1",
    "ruff>=0.8.0",
]

docs = [
    "mkdocs==1.6.1",
    "griffe==1.7.3",
    "jinja2==3.1.6",
    "mkdocstrings==0.29.1",
    "mkdocstrings-python==1.16.11",
    "mkdocs-literate-nav==0.6.2",
    "mkdocs-autorefs==1.4.2",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-material==9.6.14",
    "mkdocs-material-extensions==1.3.1",
    "mkdocs-section-index==0.3.10",
]

[tool.coverage.run]
source = ['pyiceberg/']
